#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

start=`date +%s`

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication surfaceFeatureExtract -case /home/sascha/SAIL/domain/wheelcase/hpc1_velo_changed

runApplication blockMesh -case /home/sascha/SAIL/domain/wheelcase/hpc1_velo_changed

runApplication decomposePar -case /home/sascha/SAIL/domain/wheelcase/hpc1_velo_changed
runParallel snappyHexMesh 4 -overwrite -case /home/sascha/SAIL/domain/wheelcase/hpc1_velo_changed
# foamJob -parallel -screen snappyHexMesh

meshTime=`date +%s` 
echo "$((meshTime-start))" >> mesh.timing

# #- For non-parallel running
# cp -r 0.org 0 > /dev/null 2>&1

#- For parallel running
ls -d processor* | xargs -I {} rm -rf ./{}/0
ls -d processor* | xargs -I {} cp -r 0.org ./{}/0

cfdStart=`date +%s`

runParallel patchSummary 4 -case /home/sascha/SAIL/domain/wheelcase/hpc1_velo_changed
runParallel potentialFoam 4 -case /home/sascha/SAIL/domain/wheelcase/hpc1_velo_changed
runParallel $(getApplication) 4 -case /home/sascha/SAIL/domain/wheelcase/hpc1_velo_changed

cfdEnd=`date +%s` 
echo "$((cfdEnd-cfdStart))" >> cfd.timing

runApplication reconstructParMesh -constant -case /home/sascha/SAIL/domain/wheelcase/hpc1_velo_changed
runApplication reconstructPar -latestTime -case /home/sascha/SAIL/domain/wheelcase/hpc1_velo_changed

end=`date +%s`
echo "$((end-start))" >> all.timing

# Return results
cp postProcessing/forceCoeffs1/0/forceCoeffs.dat result.dat
cp postProcessing/mirror/0/forces.dat forces.dat


# ----------------------------------------------------------------- end-of-file
